name: Run tests

on: push

jobs:
  run-ci:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: inorbit_test
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4

      # Instalação do PNPM
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Configuração do Node.js com cache do PNPM
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Instala dependências com PNPM
      - run: pnpm install

      # Executa os testes com PNPM
      - run: pnpm run test
